spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: techtemplesem
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${db.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.username}
    password: ${db.password}